---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.81
  build:
    commands:
      pip install -r requirements.txt
      python -m deploy
      mkdocs build
  artifacts":
    base-directory: site/
    files:
      - "**/*"
